export {default as MyNewsDesk} from './MyNewsDesk/MyNewsDesk'
export {default as UpdateNews} from './UpdateNews/UpdateNews'
export {default as AddNews} from './AddNews/AddNews'
export {default as NewsOneById} from './NewsOneById/NewsOneById'
export {default as TagsNews} from './TagsNews/TagsNews'
export {default as Login} from './Auth/Login/Login'
export {default as Registration} from './Auth/Registration/Registration'
export {default as MyProfile} from './MyProfile/MyProfile'
export {default as AllNews} from './AllNews/AllNews'
export {default as UpdateProfile} from './UpdateProfile/UpdateProfile'

